config/routes.rb
GF01::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  after_validation { self.errors.messages.delete(:password_digest) }

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

 def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :signed_in_user_filter, only: [:new, :create]


  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def signed_in_user_filter
      if signed_in?
        redirect_to root_path, notice: "Already logged in"
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "News Diamond"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the current time formatted nicely
  def current_time
    time = Time.new
    return time.strftime("%A, %B %d, %Y")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small class="lead"> Thank you for using News Diamond. <span><img src="assets/diamond-grey.png" height="29px" class="logo-diamond" alt="diamond logo"></span></small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">Blog</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "news diamond", root_path, id: "logo" %>
      <img src="/assets/diamond-white.png" alt="diamond logo" class="logo-diamond">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/stylesheets/bootstrap-responsive.css" rel="stylesheet">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>

<p class="about lead">
News Diamond collects the news and articles from your favorite websites in real time to create a personalized online newspaper just for you. News Diamond is designed especially for older adults, which means we took out everything distracting, unintuitive, and downright annoying (Pop-ups? We'll pass.) and instead give you a simple and powerful platform for accessing the stories you want on your terms. You're at the wisest and most knowledgeable point in your life— it's time your news caught up with you.
</p>

<div class="alert alert-info"><strong>Why the diamond?</strong> Historically, diamonds have represented 50th, 60th, and 75th anniversaries and birthdays— the perfect symbol for a beautiful platform designed for people in their 50's, 60's, 70's, and beyond.</div>


<hr class="divider">

<h1 class="page">Our Team <small>We're a family business.</small></h1>

<div class="row">
	<div class="span4">
		<img class="img-circle" alt="Chris Niles" style="width: 140px; height: 140px;" src="assets/chris.png">
		<h2>Chris Niles, CEO</h2>
		<p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
	</div>
	<div class="span4">
		<img class="img-circle" alt="Savannah Niles" style="width: 140px; height: 140px;" src="assets/savannah.png">
		<h2>Savannah Niles, CTO</h2>
		<p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
	</div>
	<div class="span4">
		<img class="img-circle" alt="Ileana Niles" style="width: 140px; height: 140px;" src="assets/ily.png">
		<h2>Ileana Niles, CFO</h2>
		<p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
	</div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us <small>We want to hear from you.</small></h1>

<p>

  <address>
	  <strong>News Diamond, Inc.</strong><br>
	  104 Blanca Meadows Ct.<br>
	  Cresson, TX 76035<br>
	  <abbr title="Phone">P:</abbr> (817) 396-0924
  </address>
 
  <address>
	<strong>Say Hello</strong><br>
	<a href="mailto:#">hello@newsdiamond.com</a>
  </address>

  <address>
	<strong>News Diamond Help</strong><br>
	<a href="mailto:#">help@newsdiamond.com</a>
  </address>

  <address>
	<strong>News Diamond Ads</strong><br>
	<a href="mailto:#">ads@newsdiamond.com</a>
  </address>

</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  This is where we'll create a robust help center with a help form and number for support.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>The news and articles you love, all in one place.</h1>

  <p class="lead">
    News Diamond is a news reader designed especially for older adults. It collects the news and articles from your favorite websites to create a personalized online newspaper just for you.
  </p>

  <%= link_to "Get started today!", signup_path, class: "btn btn-large btn-success" %>
</div>
<!-- Featurettes -->
<hr class="divider">
<div class="featurette">
	<img class="featurette-image pull-right" src="/assets/big_icon.png">
	<h2 class="featurette-heading">Hundreds of news sites and blogs. <span class="muted">Take your pick.</span></h2>
	<p class="lead">Freely subscribe to any of the hundreds of news sources, websites, and blogs available on News Diamond. Read articles from all of your favorites and then some, or discover something new based on your interests.</p>
</div>

<hr class="divider">
<div class="featurette">
	<img class="featurette-image pull-left" src="/assets/big_icon.png">
	<h2 class="featurette-heading">Just like a newspaper. <span class="muted">But so much more powerful.</span></h2>
	<p class="lead">News Diamond organizes your news from across the web into sections, just like a newspaper: browse articles in topics such as Headlines, Cooking, Business, Lifestyle, Humor, and more. And, since News Diamond collects your articles and builds you a personal paper that's updated in real time, you get the stories you want, when they break.</p>
</div>

<hr class="divider">
<div class="featurette">
	<img class="featurette-image pull-right" src="/assets/big_icon.png">
	<h2 class="featurette-heading">Reading made <span class="muted">beautiful.</span></h2>
	<p class="lead">News Diamond offers you a news-reading experience better than any other: beautiful, enjoyable, and distraction-free.</p>
</div>

<!-- row of other more minor features -->
<hr class="divider">
<div class="row">
	<div class="span4">
		<img class="img-circle" alt="Happy couple using the computer" style="width: 225px; height: 225px;" src="assets/elderly-couple-on-computer.png">
		<h2>Easy to Use</h2>
		<p>News Diamond is incredibly intuitive and easy to use, whether you've owned a computer for 20 years or 20 minutes. Got a question? Get it answered with a click of a button. Or, just give us a call.</p>
	</div>
	<div class="span4">
		<img class="img-circle" alt="Older adults around a computer" style="width: 225px; height: 225px;" src="assets/elderly-share.png">
		<h2>Share your Favorites</h2>
		<p>Star articles as Favorites or save them to a "Read Later" list to keep track of the things you love. Share stories with friends and family with a single click.</p>
	</div>
	<div class="span4">
		<img class="img-circle" alt="Happy couple" style="width: 225px; height: 225px;" src="assets/elderly-asian-couple.png">
		<h2>Always Free</h2>
		<p>News Diamond is absolutely, 100% free. You can trust that we will never share your personal information or email address. View our <a href="">Privacy Policy.</a></p>
	</div>
</div>

<div class="bottom-signup">
<%= link_to "Sign up for an account with News Diamond!", signup_path, class: "btn btn-large btn-success" %>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your Information</h1>

<div class="row">
  <div class="form">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="form">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h2><%= current_time %></h2>
<h1>Welcome, <%= @user.name %></h1>